name: Update Medium Articles

on:
  schedule:
    - cron: "0 2 * * *" # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  update-articles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4

      - name: Generate article cards
        run: |
          python .github/scripts/generate_medium_cards.py

      - name: Inject into README.md
        run: |
          python .github/scripts/inject_readme_section.py

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md README_ARTICLES.md || true
          if ! git diff --cached --quiet; then
            git commit -m "chore: update Medium articles" || echo "no commit"
            git push
          else
            echo "No changes to commit"
          fi
