name: Update Medium Articles
on:
  schedule:
    - cron: '0 2 * * *' # daily at 02:00 UTC (adjust if needed)
  workflow_dispatch:

jobs:
  fetch-medium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install feedparser beautifulsoup4

      - name: Generate article cards
        run: python .github/scripts/generate_medium_cards.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README_ARTICLES.md
          git commit -m "chore: update Medium article cards" || echo "no changes"
          git push
